fieldLayouts:
  6f0a658f-6a92-45f6-9233-a09f5a3e2780:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Info
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4e579fce-80fb-40df-a0ab-5ade3e8ecb88 # Image with Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
handle: homepage
hasTitleField: true
name: Homepage
section: a887e226-ad5b-4ffc-b54e-6bd80d70fd34 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
