field: f0b26b60-9cd6-415f-928f-c63614f6e7b8 # Content Builder
fieldLayouts:
  afd7c9ae-6b20-443f-a1f6-c6fd326a7053:
    tabs:
      -
        elements:
          -
            fieldUid: 7f794890-d66c-494d-84fc-e51a0683885c # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7f794890-d66c-494d-84fc-e51a0683885c: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richtext
name: Richtext
sortOrder: 1
