enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9eb17f17-fb0c-4688-aaff-a09782aeacea: # Craft Code Test
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
