dateModified: 1624979073
email:
  fromEmail: alex@dodgyco.de
  fromName: 'Craft Code Test'
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Craft Code Test'
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
